package com.catarsi.catosrs.util

enum class Categories(val title: String, val id: Int) {
    MISCELLANEOUS("Miscellaneous",0),
    AMMO("Ammo", 1),
    ARROWS("Arrows", 2),
    BOLTS("Bolts", 3),
    CONSTRUCTION_MATERIALS("Construction materials", 4),
    CONSTRUCTION_PRODUCTS("Construction products", 5),
    COOKING_INGREDIENTS("Cooking ingredients", 6),
    COSTUMES("Costumes", 7),
    CRAFTING_MATERIALS("Crafting materials", 8),
    FAMILIARS("Familiars", 9),
    FARMING_PRODUCE("Farming produce", 10),
    FLETCHING_MATERIALS("Fletching materials", 11),
    FOOD_AND_DRINK("Food and Drink", 12),
    HERBLORE_MATERIALS("Herblore materials", 13),
    HUNTING_EQUIPMENT("Hunting equipment", 14),
    HUNTING_PRODUCE("Hunting Produce", 15),
    JEWELLERY("Jewellery", 16),
    MAGE_ARMOUR("Mage armour", 17),
    MAGE_WEAPONS("Mage weapons", 18),
    MELEE_ARMOUR_LOW_LEVEL("Melee armour - low level", 19),
    MELEE_ARMOUR_MID_LEVEL("Melee armour - mid level", 20),
    MELEE_ARMOUR_HIGH_LEVEL("Melee armour - high level", 21),
    MELEE_WEAPONS_LOW_LEVEL("Melee weapons - low level", 22),
    MELEE_WEAPONS_MID_LEVEL("Melee weapons - mid level", 23),
    MELEE_WEAPONS_HIGH_LEVEL("Melee weapons - high level", 24),
    MINING_AND_SMITHING("Mining and Smithing", 25),
    POTIONS("Potions", 26),
    PRAYER_ARMOUR("Prayer armour", 27),
    PRAYER_MATERIALS("Prayer materials", 28),
    RANGE_ARMOUR("Range armour", 29),
    RANGE_WEAPONS("Range weapons", 30),
    RUNECRAFTING("Runecrafting", 31),
    RUNES_SPELLS_AND_TELEPORTS("Runes, Spells and Teleports", 32),
    SEEDS("Seeds", 33),
    SUMMONING_SCROLLS("Summoning scrolls", 34),
    TOOLS_AND_CONTAINERS("Tools and containers", 35),
    WOODCUTTING_PRODUCT("Woodcutting product", 36),
    POCKET_ITEMS("Pocket items", 37),
    STONE_SPIRITS("Stone spirits", 38),
    SALVAGE("Salvage", 39),
    FIREMAKING_PRODUCTS("Firemaking products", 40),
    ARCHAEOLOGY_MATERIALS("Archaeology materials", 41),
}